# -*- coding: utf-8 -*-
"""PS3Revised.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nu4eVD0UPRhcwsWMTwzKmHRoUySEoai0
"""

"""
QAM PS3: Forecasting Factor Long-Leg Excess Returns and Active Portfolio Optimization
Using
    F-F_Research_Data_Factors.csv
    Portfolios_Formed_on_ME.csv
    Portfolios_Formed_on_BE-ME.csv
    Portfolios_Formed_on_OP.csv
    Portfolios_Formed_on_INV.csv
"""

import os
import zipfile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

try:
    from pandas_datareader import data as pdr
except ImportError:
    import subprocess
    import sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas_datareader"])
    from pandas_datareader import data as pdr

try:
    import google.colab  # noqa: F401
    DATA_DIR = "/content"
except ImportError:
    DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

for zfile in [f for f in os.listdir(DATA_DIR) if f.lower().endswith(".zip")]:
    zip_path = os.path.join(DATA_DIR, zfile)
    print(f"Extracting: {zfile}")
    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall(DATA_DIR)

ff_factors_file = os.path.join(DATA_DIR, "F-F_Research_Data_Factors.csv")
size_file = os.path.join(DATA_DIR, "Portfolios_Formed_on_ME.csv")
value_file = os.path.join(DATA_DIR, "Portfolios_Formed_on_BE-ME.csv")
op_file = os.path.join(DATA_DIR, "Portfolios_Formed_on_OP.csv")
inv_file = os.path.join(DATA_DIR, "Portfolios_Formed_on_INV.csv")

for f in [ff_factors_file, size_file, value_file, op_file, inv_file]:
    print(f, "->", os.path.exists(f))

def read_ff_monthly_csv(path):
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    start_idx = None
    for i, line in enumerate(lines):
        first = line.split(",")[0].strip()
        if first.isdigit() and len(first) == 6:
            start_idx = i
            break

    if start_idx is None:
        raise ValueError(f"Could not find monthly data start in {path}")

    end_idx = None
    for i in range(start_idx, len(lines)):
        first = lines[i].split(",")[0].strip()
        if not (first.isdigit() and len(first) == 6):
            end_idx = i
            break

    if end_idx is None:
        end_idx = len(lines)

    header_line = lines[start_idx - 1].strip()
    headers = [h.strip() for h in header_line.split(",")]

    data_lines = lines[start_idx:end_idx]

    rows = []
    for line in data_lines:
        parts = [x.strip() for x in line.strip().split(",")]
        rows.append(parts)

    df = pd.DataFrame(rows, columns=headers[:len(rows[0])])
    df.rename(columns={df.columns[0]: "Date"}, inplace=True)
    df["Date"] = pd.to_datetime(df["Date"], format="%Y%m") + pd.offsets.MonthEnd(0)

    for col in df.columns[1:]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    return df.reset_index(drop=True)


ff = read_ff_monthly_csv(ff_factors_file)
size_df = read_ff_monthly_csv(size_file)
value_df = read_ff_monthly_csv(value_file)
op_df = read_ff_monthly_csv(op_file)
inv_df = read_ff_monthly_csv(inv_file)

print("FF columns:", ff.columns.tolist())
print("Size columns:", size_df.columns.tolist())
print("Value columns:", value_df.columns.tolist())
print("OP columns:", op_df.columns.tolist())
print("INV columns:", inv_df.columns.tolist())

size_col = "Lo 30"
value_col = "Hi 30"
op_col = "Hi 30"
inv_col = "Lo 30"

data = ff[["Date", "Mkt-RF", "RF"]].copy()
data = data.merge(size_df[["Date", size_col]].rename(columns={size_col: "Size_raw"}), on="Date", how="inner")
data = data.merge(value_df[["Date", value_col]].rename(columns={value_col: "Value_raw"}), on="Date", how="inner")
data = data.merge(op_df[["Date", op_col]].rename(columns={op_col: "Profitability_raw"}), on="Date", how="inner")
data = data.merge(inv_df[["Date", inv_col]].rename(columns={inv_col: "Investment_raw"}), on="Date", how="inner")

data["Market"] = data["Mkt-RF"]
data["Size"] = data["Size_raw"] - data["RF"]
data["Value"] = data["Value_raw"] - data["RF"]
data["Profitability"] = data["Profitability_raw"] - data["RF"]
data["Investment"] = data["Investment_raw"] - data["RF"]

data = data[["Date", "RF", "Market", "Size", "Value", "Profitability", "Investment"]]

# 1963:07 to 2025:06
start_date = "1963-07-31"
end_date = "2025-06-30"
data = data[(data["Date"] >= start_date) & (data["Date"] <= end_date)].copy()
data.reset_index(drop=True, inplace=True)

print(data.head())
print(data.tail())
print(data.shape)

assets = ["Market", "Size", "Value", "Profitability", "Investment"]

summary = []
for col in assets:
    mean_ann = data[col].mean() * 12
    vol_ann = data[col].std(ddof=1) * np.sqrt(12)
    sharpe = mean_ann / vol_ann
    summary.append([col, mean_ann, vol_ann, sharpe])

summary_df = pd.DataFrame(summary, columns=["Factor", "Mean (%)", "Volatility (%)", "Sharpe Ratio"])
print(summary_df)

# Macro predictors from FRED

fred_start = "1960-01-01"
fred_end = "2025-06-30"

tb3ms = pdr.DataReader("TB3MS", "fred", fred_start, fred_end).reset_index()
gs10 = pdr.DataReader("GS10", "fred", fred_start, fred_end).reset_index()
unrate = pdr.DataReader("UNRATE", "fred", fred_start, fred_end).reset_index()
payems = pdr.DataReader("PAYEMS", "fred", fred_start, fred_end).reset_index()
indpro = pdr.DataReader("INDPRO", "fred", fred_start, fred_end).reset_index()

macro = tb3ms.merge(gs10, on="DATE", how="inner")
macro = macro.merge(unrate, on="DATE", how="inner")
macro = macro.merge(payems, on="DATE", how="inner")
macro = macro.merge(indpro, on="DATE", how="inner")
macro.rename(columns={"DATE": "Date"}, inplace=True)
macro["Date"] = pd.to_datetime(macro["Date"]) + pd.offsets.MonthEnd(0)

# Term spread
macro["TERM"] = macro["GS10"] - macro["TB3MS"]

# Monthly growth rates (log growth * 100)
macro["PAYEMS_GROWTH"] = 100 * np.log(macro["PAYEMS"] / macro["PAYEMS"].shift(1))
macro["INDPRO_GROWTH"] = 100 * np.log(macro["INDPRO"] / macro["INDPRO"].shift(1))

# Lag variables by one month for publication delay
macro["UNRATE_L1"] = macro["UNRATE"].shift(1)
macro["PAYEMS_GROWTH_L1"] = macro["PAYEMS_GROWTH"].shift(1)
macro["INDPRO_GROWTH_L1"] = macro["INDPRO_GROWTH"].shift(1)

macro = macro[["Date", "TB3MS", "TERM", "UNRATE_L1", "PAYEMS_GROWTH_L1", "INDPRO_GROWTH_L1"]]

full = data.merge(macro, on="Date", how="inner").dropna().copy()
full.reset_index(drop=True, inplace=True)

print(full.head())
print(full.shape)

# Out-of-sample univariate predictive regressions and combination forecast

predictors = ["TB3MS", "TERM", "UNRATE_L1", "PAYEMS_GROWTH_L1", "INDPRO_GROWTH_L1"]
assets = ["Market", "Size", "Value", "Profitability", "Investment"]

initial_end = pd.Timestamp("1973-06-30")
oos_start = pd.Timestamp("1973-07-31")

forecast_rows = []

for i in range(len(full)):
    forecast_date = full.loc[i, "Date"]
    if forecast_date < oos_start:
        continue

    train = full[full["Date"] < forecast_date].copy()
    if train["Date"].max() < initial_end:
        continue

    row = {"Date": forecast_date}

    for asset in assets:
        actual = full.loc[i, asset]
        row[f"{asset}_actual"] = actual

        pm = train[asset].mean()
        row[f"{asset}_pm"] = pm

        indiv_forecasts = []
        for pred in predictors:
            tmp = train[[asset, pred]].dropna().copy()
            X = np.column_stack([np.ones(len(tmp)), tmp[pred].values])
            y = tmp[asset].values

            beta = np.linalg.lstsq(X, y, rcond=None)[0]

            x_next = full.loc[i, pred]
            fcast = beta[0] + beta[1] * x_next
            row[f"{asset}_{pred}_fcast"] = fcast
            indiv_forecasts.append(fcast)

        row[f"{asset}_combo"] = np.mean(indiv_forecasts)

    forecast_rows.append(row)

forecasts = pd.DataFrame(forecast_rows)
print(forecasts.head())

# Out-of-sample R^2 vs. prevailing-mean benchmark
r2_rows = []
for asset in assets:
    actual = forecasts[f"{asset}_actual"]
    pm = forecasts[f"{asset}_pm"]
    combo = forecasts[f"{asset}_combo"]

    msfe_pm = np.mean((actual - pm) ** 2)
    msfe_combo = np.mean((actual - combo) ** 2)
    r2_oos = 100 * (1 - msfe_combo / msfe_pm)

    r2_rows.append([asset, r2_oos])

r2_df = pd.DataFrame(r2_rows, columns=["Factor", "OOS_R2_percent"])
print(r2_df)

# Active portfolio optimization

gamma = 5
assets = ["Market", "Size", "Value", "Profitability", "Investment"]


def min_var_weights(cov):
    """Global minimum-variance portfolio: min w'Cov w s.t. sum(w) = 1.
    No long-only bound -- the assignment only imposes bounds on the active
    weight differential x, not on the benchmark weights w."""
    n = cov.shape[0]

    def obj(w):
        return w @ cov @ w

    cons = [{"type": "eq", "fun": lambda w: np.sum(w) - 1}]
    w0 = np.ones(n) / n

    res = minimize(obj, w0, constraints=cons)
    return res.x


def active_weights(mu, cov, gamma=5):
    """Active weight differential x, solved on DECIMAL-return scale so that
    gamma=5 is the intended risk-aversion magnitude. mu/cov here come in as
    percent (Ken French convention), so divide by 100 / 100^2 before
    optimizing -- weights are unit-free, so nothing downstream changes."""
    n = len(mu)
    mu_dec = mu / 100.0
    cov_dec = cov / 100.0 ** 2

    def obj(x):
        return -(x @ mu_dec - 0.5 * gamma * (x @ cov_dec @ x))

    cons = [{"type": "eq", "fun": lambda x: np.sum(x)}]
    bounds = [(-0.5, 0.5)] * n
    x0 = np.zeros(n)

    res = minimize(obj, x0, bounds=bounds, constraints=cons)
    return res.x


portfolio_rows = []

for _, row in forecasts.iterrows():
    date = row["Date"]

    hist = full[full["Date"] < date][assets].dropna().copy()
    cov = hist.cov().values

    mu = np.array([row[f"{a}_combo"] for a in assets])
    actual_ret = np.array([row[f"{a}_actual"] for a in assets])

    wb = min_var_weights(cov)
    x = active_weights(mu, cov, gamma=gamma)
    wa = wb + x

    bench_ret = wb @ actual_ret
    active_ret = wa @ actual_ret
    outperf = active_ret - bench_ret

    portfolio_rows.append({
        "Date": date,
        "Benchmark_ret": bench_ret,
        "Active_ret": active_ret,
        "Outperformance": outperf,
    })

port = pd.DataFrame(portfolio_rows)
print(port.head())


def ann_stats(series):
    mean_ann = series.mean() * 12
    vol_ann = series.std(ddof=1) * np.sqrt(12)
    sharpe = mean_ann / vol_ann
    return mean_ann, vol_ann, sharpe


bench_mean, bench_vol, bench_sharpe = ann_stats(port["Benchmark_ret"])
act_mean, act_vol, act_sharpe = ann_stats(port["Active_ret"])

portfolio_summary = pd.DataFrame({
    "Portfolio": ["Benchmark", "Active"],
    "Mean (%)": [bench_mean, act_mean],
    "Volatility (%)": [bench_vol, act_vol],
    "Sharpe Ratio": [bench_sharpe, act_sharpe],
})
print(portfolio_summary)

outperf_ann = port["Outperformance"].mean() * 12
tracking_error_ann = port["Outperformance"].std(ddof=1) * np.sqrt(12)
information_ratio = outperf_ann / tracking_error_ann

active_stats = pd.DataFrame({
    "Metric": ["Outperformance (%)", "Tracking Error (%)", "Information Ratio"],
    "Value": [outperf_ann, tracking_error_ann, information_ratio],
})
print(active_stats)

port["Benchmark_log_cum"] = np.log1p(port["Benchmark_ret"] / 100).cumsum()
port["Active_log_cum"] = np.log1p(port["Active_ret"] / 100).cumsum()

# NBER recession shading

recession = pdr.DataReader("USREC", "fred", "1973-07-01", "2025-06-30").reset_index()
recession.rename(columns={"DATE": "Date"}, inplace=True)
recession["Date"] = pd.to_datetime(recession["Date"]) + pd.offsets.MonthEnd(0)

plot_df = port.merge(recession, on="Date", how="left")

plt.figure(figsize=(12, 6))
plt.plot(plot_df["Date"], plot_df["Benchmark_log_cum"], label="Benchmark (minimum variance)")
plt.plot(plot_df["Date"], plot_df["Active_log_cum"], label="Active")

in_recession = False
start_date = None
for i in range(len(plot_df)):
    rec = plot_df.loc[i, "USREC"]
    date = plot_df.loc[i, "Date"]

    if rec == 1 and not in_recession:
        in_recession = True
        start_date = date
    elif rec == 0 and in_recession:
        in_recession = False
        plt.axvspan(start_date, date, alpha=0.2)

if in_recession:
    plt.axvspan(start_date, plot_df["Date"].iloc[-1], alpha=0.2)

plt.title("Log Cumulative Portfolio Excess Returns")
plt.xlabel("Date")
plt.ylabel("Log cumulative excess return")
plt.legend()
plt.grid(True)
plt.savefig(os.path.join(os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else ".", "log_cum_returns.png"), dpi=150)
plt.show()

# outputs

summary_df_rounded = summary_df.copy()
for col in ["Mean (%)", "Volatility (%)", "Sharpe Ratio"]:
    summary_df_rounded[col] = summary_df_rounded[col].round(2)

r2_df_rounded = r2_df.copy()
r2_df_rounded["OOS_R2_percent"] = r2_df_rounded["OOS_R2_percent"].round(2)

portfolio_summary_rounded = portfolio_summary.copy()
for col in ["Mean (%)", "Volatility (%)", "Sharpe Ratio"]:
    portfolio_summary_rounded[col] = portfolio_summary_rounded[col].round(2)

active_stats_rounded = active_stats.copy()
active_stats_rounded["Value"] = active_stats_rounded["Value"].round(3)

print(summary_df_rounded)
print(r2_df_rounded)
print(portfolio_summary_rounded)
print(active_stats_rounded)

out_path = os.path.join(DATA_DIR, "ps3_results.xlsx")
with pd.ExcelWriter(out_path) as writer:
    summary_df_rounded.to_excel(writer, sheet_name="Factor_Summary", index=False)
    r2_df_rounded.to_excel(writer, sheet_name="OOS_R2", index=False)
    portfolio_summary_rounded.to_excel(writer, sheet_name="Portfolio_Summary", index=False)
    active_stats_rounded.to_excel(writer, sheet_name="Active_vs_Benchmark", index=False)

print(f"Saved results to {out_path}")