# -*- coding: utf-8 -*-
"""DataProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbA0lO2DPdREBOvTjIxabwfgxPSloVRq
"""

!pip install wrds

import wrds
import pandas as pd
import numpy as np

db = wrds.Connection()

# Pull 5 rows and inspect available columns
sample = db.get_table('crsp', 'msf', obs=5)

print("Number of columns:", len(sample.columns))
print("\nColumns:\n")
for col in sample.columns:
    print(col)

sample.head()

import statsmodels.api as sm

db = wrds.Connection()

query = """
SELECT
    msf.permno,
    msf.permco,
    msf.date,
    msf.ret,
    msf.prc,
    msf.shrout,
    msf.vol,
    msf.hexcd,
    msf.hsiccd
FROM crsp.msf AS msf
WHERE msf.date BETWEEN '1989-01-01' AND '2024-12-31'
ORDER BY msf.permno, msf.date
"""

crsp = db.raw_sql(query, date_cols=["date"])

print(crsp.shape)
print(crsp.head())

crsp["ret"] = pd.to_numeric(crsp["ret"], errors="coerce")
crsp["prc"] = pd.to_numeric(crsp["prc"], errors="coerce")
crsp["shrout"] = pd.to_numeric(crsp["shrout"], errors="coerce")

# NYSE, AMEX, NASDAQ using CRSP exchange code
crsp = crsp[crsp["hexcd"].isin([1, 2, 3])].copy()

crsp["me"] = crsp["prc"].abs() * crsp["shrout"]

crsp["month"] = crsp["date"].dt.to_period("M").dt.to_timestamp("M")

crsp = crsp.sort_values(["permno", "month"])

crsp["gross_ret"] = 1 + crsp["ret"]

crsp["mom_12_2"] = (
    crsp.groupby("permno")["gross_ret"]
    .rolling(window=11, min_periods=8)
    .apply(np.prod, raw=True)
    .reset_index(level=0, drop=True)
    - 1
)

crsp["mom_12_2"] = crsp.groupby("permno")["mom_12_2"].shift(2)

crsp = crsp[
    (crsp["month"] >= "1990-01-31") &
    (crsp["month"] <= "2024-12-31") &
    (crsp["ret"].notna()) &
    (crsp["mom_12_2"].notna())
].copy()

print(crsp.shape)
crsp.head()

# momentum deciles for each month
def assign_deciles(x):
    try:
        return pd.qcut(x, 10, labels=False, duplicates="drop") + 1
    except:
        return np.nan

crsp["mom_decile"] = crsp.groupby("month")["mom_12_2"].transform(assign_deciles)

# Equal-weighted decile returns
decile_returns = (
    crsp.dropna(subset=["mom_decile"])
    .groupby(["month", "mom_decile"])["ret"]
    .mean()
    .reset_index()
)

decile_wide = decile_returns.pivot(index="month", columns="mom_decile", values="ret")

# Winner = decile 10, Loser = decile 1
decile_wide["Winner"] = decile_wide[10]
decile_wide["Loser"] = decile_wide[1]
decile_wide["WML"] = decile_wide["Winner"] - decile_wide["Loser"]

decile_wide.head()

def summarize_returns(series):
    series = series.dropna()
    mean_monthly = series.mean()
    std_monthly = series.std()
    t_stat = mean_monthly / (std_monthly / np.sqrt(len(series)))
    annualized_return = (1 + mean_monthly) ** 12 - 1
    annualized_vol = std_monthly * np.sqrt(12)
    sharpe = annualized_return / annualized_vol

    return pd.Series({
        "Mean Monthly Return": mean_monthly,
        "Monthly Std Dev": std_monthly,
        "t-stat": t_stat,
        "Annualized Return": annualized_return,
        "Annualized Volatility": annualized_vol,
        "Sharpe Ratio": sharpe,
        "N Months": len(series)
    })

results = pd.DataFrame({
    "Losers": summarize_returns(decile_wide["Loser"]),
    "Winners": summarize_returns(decile_wide["Winner"]),
    "Winner-Loser": summarize_returns(decile_wide["WML"])
}).T

results_percent = results.copy()
for col in ["Mean Monthly Return", "Monthly Std Dev", "Annualized Return", "Annualized Volatility"]:
    results_percent[col] = results_percent[col] * 100

results_percent.round(3)

#exploratory
cum_wml = (1 + decile_wide["WML"]).cumprod()

cum_wml.plot(figsize=(10,6))
plt.title("Momentum Strategy Cumulative Wealth")
plt.ylabel("Growth of $1")
plt.show()

#exploratory
pre_2005 = decile_wide.loc[:'2004-12-31', 'WML']
post_2005 = decile_wide.loc['2005-01-01':, 'WML']

for name, data in [("1990-2004", pre_2005),
                   ("2005-2024", post_2005)]:
    mean = data.mean()*100
    t = data.mean()/(data.std()/np.sqrt(len(data)))
    print(name, mean, t)

ff3 = pd.read_csv(
    "/content/sample_data/F-F_Research_Data_Factors.csv",
    skiprows=3
)

ff3.columns = ["date","MKT_RF","SMB","HML","RF"]

ff3 = ff3[
    ff3["date"].astype(str).str.match(r"^\d{6}$")
].copy()

ff3["date"] = pd.to_datetime(
    ff3["date"].astype(str),
    format="%Y%m"
) + pd.offsets.MonthEnd(0)

for col in ["MKT_RF","SMB","HML","RF"]:
    ff3[col] = pd.to_numeric(ff3[col], errors="coerce") / 100

ff3.head()

decile_wide["WML"]

momentum = decile_wide[["WML"]].copy()

momentum = momentum.reset_index()

momentum.head()

ff_data = momentum.merge(
    ff3,
    left_on="month",
    right_on="date",
    how="inner"
)

ff_data.head()

ff_data["WML_EXCESS"] = ff_data["WML"]

X = ff_data[["MKT_RF","SMB","HML"]]

X = sm.add_constant(X)

y = ff_data["WML_EXCESS"]

model = sm.OLS(y, X).fit()

print(model.summary())